### ISSUE TITLE
why my workflow exit with code 1 when pull request?

### ISSUE THREAD

**Issue by mtcoafun** [seriousben/go-patch-cover-action#11]
I set yml just like your readme, but exit when pull request.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/50589627/156578460-cd566f40-0df7-4337-8079-f78c198c3838.png">

howerver, it works when normal push...

<img width="422" alt="image" src="https://user-images.githubusercontent.com/50589627/156578924-8be1c9fc-1c7a-41dd-a13e-3197495bf925.png">

**Comment by seriousben** [comment]
Thanks for reporting this issue, there seem to be a change in behavior with the GitHub CLI that prevents creation of comment from within the action because of a new validation.

I will do more investigation and will report back.

**Comment by mtcoafun** [comment]
> 

appreciate it, wait for your solution😃

**Comment by seriousben** [comment]
Fixed by https://github.com/seriousben/go-patch-cover-action/pull/12 - Will be releasing a new version within the next minutes.
